spring:
  profiles:
    active: default
    include:
      - common
      - catalog


---

spring:
  jackson:
    mapper:
      default-view-inclusion: true
    serialization:
      indent-output: true

  mvc:
    throw-exception-if-no-handler-found: true